config/routes.rb
RailsDevisePundit::Application.routes.draw do
  
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :tasks

  post 'users/:id/assign' => 'users#assign', as: :assign_tasks
  post 'tasks/:id/shuffle' => 'tasks#shuffle', as: :shuffle_tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :id, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :completed, presence: false
  validates :roman, presence: true
  validates :deadline, presence: true

  has_many :task_assignments
  has_many :users, through: :task_assignments


  def self.shuffle_task_for (task)
    task.task_assignments.each do |tskas|
      tskas.update(user_id: User.maximum("completed_tasks"))
    end
  end


  def self.romanize_for (tasks)
    roman_numbers = {
      1000 => 'M',
      900 => 'CM',
      500 => 'D',
      400 => 'CD',
      100 => 'C',
      90 => 'XC',
      50 => 'L',
      40 => 'XL',
      10 => 'X',
      9 => 'IX',
      5 => 'V',
      4 => 'IV',
      1 => 'I',
    }

    tasks.each do |t|
      number = t.id
      result = ''
      while number > 0
        roman_numbers.each do |arab, roman|
          if number / arab >= 1
            result << roman
            number -= arab
           break
          end
        end
      end

      t.update(roman: result)
    end
  end


end

app/models/task_assignment.rb
class TaskAssignment < ActiveRecord::Base
	belongs_to :user
	belongs_to :task

	validates :user, :presence => true
	validates :task, :presence => true

	validates_uniqueness_of :user_id, :scope => :task_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :task_assignments
  has_many :tasks, through: :task_assignments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?


  def set_default_role
    self.role ||= :user
  end

  
  def self.count_tasks_for (user)
    finished = 0
    user.tasks.each do |task|
      if task.completed == true
        finished +=1
      end
    end
    user.update(completed_tasks: finished)
  end
    

  def self.assign_task_for (user)
    if (user.tasks.count < 5) 
      n = rand(1..(5-user.tasks.count))
      n.times do 
        TaskAssignment.create(
          user_id: user.id,
          task_id: rand(1..Task.count)
        )
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  

  
  private

  def user_not_authorized
    flash[:alert] = "Access denied."
    redirect_to (request.referrer || root_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @users = User.all
    @tasks = Task.all
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :romanize_for,  only: [:index, :show, :edit, :update, :destroy]
  respond_to :html, :json, :js
  

  def index
    respond_with(@tasks = Task.all)

  end


  def show    
  end


  def new
    @task = Task.new
  end


  def edit
  end

  def shuffle
    task = Task.find(params[:id]) 
    Task.shuffle_task_for task

    redirect_to task_path, notice: "Task shuffled!"
  end


  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_task
      @task = Task.find(params[:id])
    end

    def romanize_for
      tasks = Task.all
      Task.romanize_for tasks
    end

    def task_params
      params.require(:task).permit(:name, :description, :completed, :roman, :deadline)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!  
  before_action :set_user, only: [:show, :edit, :update, :destroy, :assign]
  after_action :verify_authorized, except: [:show, :assign]
  respond_to :html, :js, :json

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    @tasks = Task.all
  end

  def update
    authorize user
    if user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize user
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  def assign
    user = User.find(params[:id]) 
    User.assign_task_for user
    
    respond_to do |format|
			if request.xhr?    
    		format.html { redirect_to @user, notice: 'Task was successfully assigned.' }
        format.json { render action: 'show', status: :created, location: @user }
        format.js   { render action: 'show', status: :created, location: @user }
			else
        format.html { render action: 'show' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js   { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    #redirect_to user_path, notice: "Tasks assigned!"
  end
    

    private

    def set_user
        user = User.find(params[:id])
        User.count_tasks_for (user)
    end

    def secure_params
      params.require(:user).permit(:role, :email, :completed_tasks)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<h3>Home</h3>
<% if !current_user.nil?# and current_user.admin? %>
  <% @users.each do |user| %>
  	<% if current_user == user %>
      <p>User: <%=link_to user.email, user %> Role: <%= user.role unless user.role.nil? %> ID: <%= user.id %></p>
  		
  		<%#= link_to 'Assign', :controller => :user, :action => :assign, :id => user.id %>

		

    <% end %>  
  <% end %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Todo Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Todo Application" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label "Completed?" %>
    <%= f.check_box :completed %>
  </div>
  <%#= link_to("Change completed status", task_path(f, "task[completed]" => true), :method => :put, :confirm => "Sure?") %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %>
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>  
      <th>ID Roman</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.roman %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Task:</h1>
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Completed?:</strong>
  <%= @task.completed? %>
</p>

<p>
  <strong>Roman ID:</strong>
  <%= @task.roman %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %> |
<%= button_to 'SHUFFLE', shuffle_tasks_path %>

<!--<p>
  <strong>Users:</strong>  
  <%#= @task.task_assignments.collect { |t| t.user } %>  
</p>
-->

<% @task.task_assignments.each do |tskas| %>
	<%= tskas.id %>
	<%= tskas.user_id %>
	<%= tskas.task_id %>
<% end %>

<h2>Listing Users For This Task</h2>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>ID</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
	<% @task.users.each do |user| %>
	  <tr>
        <td><%= link_to user.email, user %></td>
        <td><%= user.id %></td>
        <td><%#= link_to 'Show', user %></td>        
	  </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/_user_tasks.html.erb
<tr id='parti'>
  <td><%= task.name %></td>
  <td><%= task.description %></td>
  <td><%= task.completed? %></td>
  <td><%= task.roman %></td>
  <td><%= link_to 'Show', task %></td>
  <td><%= link_to 'Edit', edit_task_path(task) %></td>
  <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/users/assign.html.erb
<%= 1+1 %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if !current_user.nil? and current_user == @user or current_user.admin? %>
  <h3>User</h3>
  <p>Email: <%= @user.email if @user.email %></p>
  <p>Completed Tasks: <%= @user.completed_tasks %></p>  <%#@user.completed_tasks%>

  <!--<p>
  <strong>Tasks:</strong>  
    <%#= @user.task_assignments.collect { |u| u.task.name } %>  
  </p>
-->

  <h1>Listing Tasks For This User</h1>

<table id='task_table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Completed</th>
      <th>Roman ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.tasks.each do |task| %>
	    <%= render partial: 'user_tasks', locals: {task: task} %>
    <% end %>
  </tbody>
</table>

  <%= button_to 'ASSIGN TASKS', assign_tasks_path, form: { id: "assign"}, remote: true %>

<% end %> 

app/views/users/show.js.erb
<%# require './lib/assets_helper.rb' %>
<%# part = partial('./views/users/_user_tasks', :var1 => true, :var2 => false) %>

//$(document).ready(function() {
//    $('#assign').click(function() {
 //       $('#task_table').append("<%= j render(partial: 'user_tasks', locals: {task: @task}); %>");
        
  //  });
//});
$('#assign').click(function() {
	$("<%= j (render @user.tasks) %>").appendTo("#parti");
});